/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.example.inventory.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the OrderRow service. Represents a row in the &quot;OrderForm_OrderRow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.inventory.model.impl.OrderRowModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.inventory.model.impl.OrderRowImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrderRow
 * @see com.example.inventory.model.impl.OrderRowImpl
 * @see com.example.inventory.model.impl.OrderRowModelImpl
 * @generated
 */
@ProviderType
public interface OrderRowModel extends BaseModel<OrderRow> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order row model instance should use the {@link OrderRow} interface instead.
	 */

	/**
	 * Returns the primary key of this order row.
	 *
	 * @return the primary key of this order row
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order row.
	 *
	 * @param primaryKey the primary key of this order row
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the order row ID of this order row.
	 *
	 * @return the order row ID of this order row
	 */
	public long getOrderRowId();

	/**
	 * Sets the order row ID of this order row.
	 *
	 * @param orderRowId the order row ID of this order row
	 */
	public void setOrderRowId(long orderRowId);

	/**
	 * Returns the order ID of this order row.
	 *
	 * @return the order ID of this order row
	 */
	public long getOrderId();

	/**
	 * Sets the order ID of this order row.
	 *
	 * @param orderId the order ID of this order row
	 */
	public void setOrderId(long orderId);

	/**
	 * Returns the product code of this order row.
	 *
	 * @return the product code of this order row
	 */
	@AutoEscape
	public String getProductCode();

	/**
	 * Sets the product code of this order row.
	 *
	 * @param productCode the product code of this order row
	 */
	public void setProductCode(String productCode);

	/**
	 * Returns the product ean of this order row.
	 *
	 * @return the product ean of this order row
	 */
	@AutoEscape
	public String getProductEAN();

	/**
	 * Sets the product ean of this order row.
	 *
	 * @param productEAN the product ean of this order row
	 */
	public void setProductEAN(String productEAN);

	/**
	 * Returns the product name of this order row.
	 *
	 * @return the product name of this order row
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this order row.
	 *
	 * @param productName the product name of this order row
	 */
	public void setProductName(String productName);

	/**
	 * Returns the product price group of this order row.
	 *
	 * @return the product price group of this order row
	 */
	@AutoEscape
	public String getProductPriceGroup();

	/**
	 * Sets the product price group of this order row.
	 *
	 * @param productPriceGroup the product price group of this order row
	 */
	public void setProductPriceGroup(String productPriceGroup);

	/**
	 * Returns the product discounted price of this order row.
	 *
	 * @return the product discounted price of this order row
	 */
	public double getProductDiscountedPrice();

	/**
	 * Sets the product discounted price of this order row.
	 *
	 * @param productDiscountedPrice the product discounted price of this order row
	 */
	public void setProductDiscountedPrice(double productDiscountedPrice);

	/**
	 * Returns the product no vat price of this order row.
	 *
	 * @return the product no vat price of this order row
	 */
	public double getProductNoVatPrice();

	/**
	 * Sets the product no vat price of this order row.
	 *
	 * @param productNoVatPrice the product no vat price of this order row
	 */
	public void setProductNoVatPrice(double productNoVatPrice);

	/**
	 * Returns the product no vat discounted price of this order row.
	 *
	 * @return the product no vat discounted price of this order row
	 */
	public double getProductNoVatDiscountedPrice();

	/**
	 * Sets the product no vat discounted price of this order row.
	 *
	 * @param productNoVatDiscountedPrice the product no vat discounted price of this order row
	 */
	public void setProductNoVatDiscountedPrice(
		double productNoVatDiscountedPrice);

	/**
	 * Returns the product weight of this order row.
	 *
	 * @return the product weight of this order row
	 */
	public double getProductWeight();

	/**
	 * Sets the product weight of this order row.
	 *
	 * @param productWeight the product weight of this order row
	 */
	public void setProductWeight(double productWeight);

	/**
	 * Returns the use lots of this order row.
	 *
	 * @return the use lots of this order row
	 */
	public boolean getUseLots();

	/**
	 * Returns <code>true</code> if this order row is use lots.
	 *
	 * @return <code>true</code> if this order row is use lots; <code>false</code> otherwise
	 */
	public boolean isUseLots();

	/**
	 * Sets whether this order row is use lots.
	 *
	 * @param useLots the use lots of this order row
	 */
	public void setUseLots(boolean useLots);

	/**
	 * Returns the order lots of this order row.
	 *
	 * @return the order lots of this order row
	 */
	public double getOrderLots();

	/**
	 * Sets the order lots of this order row.
	 *
	 * @param orderLots the order lots of this order row
	 */
	public void setOrderLots(double orderLots);

	/**
	 * Returns the lot size of this order row.
	 *
	 * @return the lot size of this order row
	 */
	public double getLotSize();

	/**
	 * Sets the lot size of this order row.
	 *
	 * @param lotSize the lot size of this order row
	 */
	public void setLotSize(double lotSize);

	/**
	 * Returns the order amount of this order row.
	 *
	 * @return the order amount of this order row
	 */
	public double getOrderAmount();

	/**
	 * Sets the order amount of this order row.
	 *
	 * @param orderAmount the order amount of this order row
	 */
	public void setOrderAmount(double orderAmount);

	/**
	 * Returns the previous amount of this order row.
	 *
	 * @return the previous amount of this order row
	 */
	public double getPreviousAmount();

	/**
	 * Sets the previous amount of this order row.
	 *
	 * @param previousAmount the previous amount of this order row
	 */
	public void setPreviousAmount(double previousAmount);

	/**
	 * Returns the previous months of this order row.
	 *
	 * @return the previous months of this order row
	 */
	public double getPreviousMonths();

	/**
	 * Sets the previous months of this order row.
	 *
	 * @param previousMonths the previous months of this order row
	 */
	public void setPreviousMonths(double previousMonths);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OrderRow orderRow);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OrderRow> toCacheModel();

	@Override
	public OrderRow toEscapedModel();

	@Override
	public OrderRow toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}