/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.example.inventory.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Order service. Represents a row in the &quot;OrderForm_Order&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.inventory.model.impl.OrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.inventory.model.impl.OrderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Order
 * @see com.example.inventory.model.impl.OrderImpl
 * @see com.example.inventory.model.impl.OrderModelImpl
 * @generated
 */
@ProviderType
public interface OrderModel extends BaseModel<Order> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order model instance should use the {@link Order} interface instead.
	 */

	/**
	 * Returns the primary key of this order.
	 *
	 * @return the primary key of this order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order.
	 *
	 * @param primaryKey the primary key of this order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the order ID of this order.
	 *
	 * @return the order ID of this order
	 */
	public long getOrderId();

	/**
	 * Sets the order ID of this order.
	 *
	 * @param orderId the order ID of this order
	 */
	public void setOrderId(long orderId);

	/**
	 * Returns the seller of this order.
	 *
	 * @return the seller of this order
	 */
	@AutoEscape
	public String getSeller();

	/**
	 * Sets the seller of this order.
	 *
	 * @param seller the seller of this order
	 */
	public void setSeller(String seller);

	/**
	 * Returns the order date of this order.
	 *
	 * @return the order date of this order
	 */
	public Date getOrderDate();

	/**
	 * Sets the order date of this order.
	 *
	 * @param orderDate the order date of this order
	 */
	public void setOrderDate(Date orderDate);

	/**
	 * Returns the delivery week of this order.
	 *
	 * @return the delivery week of this order
	 */
	@AutoEscape
	public String getDeliveryWeek();

	/**
	 * Sets the delivery week of this order.
	 *
	 * @param deliveryWeek the delivery week of this order
	 */
	public void setDeliveryWeek(String deliveryWeek);

	/**
	 * Returns the vat percent text of this order.
	 *
	 * @return the vat percent text of this order
	 */
	@AutoEscape
	public String getVatPercentText();

	/**
	 * Sets the vat percent text of this order.
	 *
	 * @param vatPercentText the vat percent text of this order
	 */
	public void setVatPercentText(String vatPercentText);

	/**
	 * Returns the vat factor of this order.
	 *
	 * @return the vat factor of this order
	 */
	public double getVatFactor();

	/**
	 * Sets the vat factor of this order.
	 *
	 * @param vatFactor the vat factor of this order
	 */
	public void setVatFactor(double vatFactor);

	/**
	 * Returns the total weight of this order.
	 *
	 * @return the total weight of this order
	 */
	public double getTotalWeight();

	/**
	 * Sets the total weight of this order.
	 *
	 * @param totalWeight the total weight of this order
	 */
	public void setTotalWeight(double totalWeight);

	/**
	 * Returns the additional info of this order.
	 *
	 * @return the additional info of this order
	 */
	@AutoEscape
	public String getAdditionalInfo();

	/**
	 * Sets the additional info of this order.
	 *
	 * @param additionalInfo the additional info of this order
	 */
	public void setAdditionalInfo(String additionalInfo);

	/**
	 * Returns the rep email of this order.
	 *
	 * @return the rep email of this order
	 */
	@AutoEscape
	public String getRepEmail();

	/**
	 * Sets the rep email of this order.
	 *
	 * @param repEmail the rep email of this order
	 */
	public void setRepEmail(String repEmail);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Order order);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Order> toCacheModel();

	@Override
	public Order toEscapedModel();

	@Override
	public Order toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}