create table Inventory_Product (
	id_ LONG not null primary key,
	code_ VARCHAR(75) null,
	name VARCHAR(75) null
);

create table OrderForm_Order (
	orderId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	createDate DATE null,
	orderNumber LONG,
	storeCustomerNumber VARCHAR(75) null,
	seller VARCHAR(75) null,
	orderDate DATE null,
	deliveryDate DATE null,
	deliveryWeek VARCHAR(75) null,
	sendConfirmation BOOLEAN,
	customerContactEmail VARCHAR(75) null,
	customerContactName VARCHAR(75) null,
	customerContactPhone VARCHAR(75) null,
	customerName VARCHAR(75) null,
	customerAddress VARCHAR(75) null,
	customerPostalCode VARCHAR(75) null,
	customerPostOffice VARCHAR(75) null,
	vatPercentText VARCHAR(75) null,
	vatFactor DOUBLE,
	totalWeight DOUBLE,
	sellerNotes VARCHAR(75) null,
	additionalInfo VARCHAR(75) null,
	repEmail VARCHAR(75) null,
	signatureImage VARCHAR(75) null,
	signatureClarification VARCHAR(75) null,
	auditKeyup VARCHAR(75) null
);

create table OrderForm_OrderRow (
	orderRowId LONG not null primary key,
	orderId LONG,
	groupId LONG,
	companyId LONG,
	productCode VARCHAR(75) null,
	productEAN VARCHAR(75) null,
	productName VARCHAR(75) null,
	productPriceGroup VARCHAR(75) null,
	productSpecialPrice DOUBLE,
	productDiscountedPrice DOUBLE,
	productNoVatPrice DOUBLE,
	productNoVatDiscountedPrice DOUBLE,
	productWeight DOUBLE,
	useLots BOOLEAN,
	orderLots DOUBLE,
	lotSize DOUBLE,
	orderAmount DOUBLE,
	deliveredAmount DOUBLE,
	returnedAmount DOUBLE,
	previousAmount DOUBLE,
	previousMonths DOUBLE,
	previousThreeDays DOUBLE,
	previousSevenDays DOUBLE,
	spoilagePct DOUBLE,
	extraInfo VARCHAR(75) null,
	fixedRow BOOLEAN
);